### ISSUE TITLE
Security vulnerabilities detected in Pillow

### ISSUE THREAD

**Issue by leehart** [malariagen/pf-haploatlas#19]
Re: https://github.com/malariagen/pf-haploatlas/security/dependabot

- 2 critical severity
  - https://github.com/malariagen/pf-haploatlas/security/dependabot/1
  - https://github.com/malariagen/pf-haploatlas/security/dependabot/2
- 5 high severity
- 2 moderate severity

**Comment by Chiyun-Lee** [comment]
Thanks @leehart . Resolving this since we've removed Pillow from our requirements.txt as we no longer use the package anyway.
